### ISSUE TITLE
Creating target for tvOS

### ISSUE THREAD

**Issue by robreuss** [IBM-Swift/BlueSocket#100]
Any tips or a sample project for creating a tvOS target?  

I've based my tvOS target on the iOS target.  The target name is Socket-tvOS and I've modified the Project Module Name setting to be "Socket".  Nevertheless, my framework project that contains BlueSocket does not compile because it cannot find the "Socket" module ("No such module 'Socket'").  I've done my best to carefully confirm all of the settings in my own tvOS framework project that utilizes BlueSocket are correct and match the settings for the iOS version of my framework.

Any suggestions?  Thanks in advance.

**Comment by robreuss** [comment]
I should note that the tvOS BlueSocket target I created **does** compile and produce a target.  It is simply that my framework cannot see it even though it is added to it's target.  My guess is that I've done something wrong in ensuring that BlueSocket tvOS target has the correct module name.

**Comment by billabt** [comment]
I've added a _new tvOS target_ to the latest version, _0.12.77_.  Tested here and it seems to be fine.  Re-open the issue if you have an problems.

**Comment by robreuss** [comment]
Works.  Thank you sir.
