### ISSUE TITLE
Detect Close_Wait state

### ISSUE THREAD

**Issue by euwars** [IBM-Swift/BlueSocket#102]
In my project I'm using [Kassandra](https://github.com/IBM-Swift-Sunset/Kassandra), Which uses BlueSocket. 
In my testings, after establishing the initial connection. When i stop the cassandra service, in Xcode i see the connection state changing to "CloseWait", but socket doesn't represent it.
In other words, when connection state is "CloseWait", Socket returns true to isConnected, isActive and isListening.

My question is, Is this an expected behaviour and if so how can i detect the "CloseWait" state.

**Comment by billabt** [comment]
First question, did you _close the Socket_?  That should handle it.  The **CLOSE_WAIT** TCP state means that the local end of the connection has received a **FIN** from the other end, but the OS is waiting for the program at the _local end_ (i.e. your program) to actually close its connection. A simple _socket.close()_ should do the trick.  Feel free to re-open this issue if this doesn't solve it for you.
