### ISSUE TITLE
when i try to create a connect to server , it always not permitted, how to solve it ?

### ISSUE THREAD

**Issue by vikivae** [IBM-Swift/BlueSocket#103]
Error code: -9989(0x-2705), Operation not permitted

class conect {
    var mysocket:Socket?
    func sss(){
        
        do{
            mysocket = try Socket.create()
            try mysocket?.connect(to: "192.168.1.131", port: 31500)
            
            
            
        }catch {
            print(error)
        }
        print(mysocket?.isConnected as Any)
        print(mysocket?.isActive as Any)

    }
    
}

conect().sss()

**Comment by billabt** [comment]
I've tried to reproduce this on my systems and so far have been unable to.  The only differences are the parameters to the _connect_ function.  It seems to connect without fail all the time.  What is it that you're trying to connect to?  Once I know that, I can try and reproduce it here.

**Comment by billabt** [comment]
Any updates on this from your end?  Is it resolved?  Please let me know so we can either investigate further or close the issue. Thanks.

**Comment by TheSnowFox** [comment]
Hi, 
I don't know if I should post on this tread or create a new one, but I think I have the same problem.
When I try to connect to my server from a Cocoa App project, I get:
`Error code: -9989(0x-2705), Operation not permitted`

I tried from command line project and it works perfectly...

Here is my code for the Cocoa App (Simple new project created from Xcode, without any multithread, just for testing...):
```swift
import Cocoa
import Socket

@NSApplicationMain
class AppDelegate: NSObject, NSApplicationDelegate {
    
    var socket: Socket!
    
    func applicationDidFinishLaunching(_ aNotification: Notification) {
        // Insert code here to initialize your application
        
        //Connect to server
        do {
            socket = try Socket.create()
            try socket.connect(to: "127.0.0.1", port: 22560)
            sleep(10)
            socket.close()
        } catch let error {
            switch error {
            case is Socket.Error: print((error as! Socket.Error).description)
            default: print(error.localizedDescription)
            }
        }
    }

    func applicationWillTerminate(_ aNotification: Notification) {
        // Insert code here to tear down your application
    }


}
```

And the code that works in command line project:
```swift
import Foundation
import Socket

let socket: Socket!
let bufferSize = 4096

do {
    socket = try Socket.create()
    try socket.connect(to: "127.0.0.1", port: 22560)
    sleep(10)
    socket.close()
} catch let error {
    switch error {
    case is Socket.Error: print((error as! Socket.Error).description)
    default: print(error.localizedDescription)
    }
}
```

Thank you in advance !

**Comment by shmuelk** [comment]
Isn't 127.0.0.1 on an iPhone, the phone itself? Maybe not in the simulator, if that's where you're trying to run the app.

**Comment by TheSnowFox** [comment]
No it's a mac app.

**Comment by TheSnowFox** [comment]
I think I have found the answer. 
In new versions of Xcode, I need to go to MyProject > target MyApp > capabilities > App Sandbox > check  Network Outgoing Connections (Client)
 I think it is closed for me...
Thanks

**Comment by billabt** [comment]
Makes sense...  Thanks for the update.
