### ISSUE TITLE
read(into: inout Data) resulting in Error -9982 Interrupted System Call

### ISSUE THREAD

**Issue by qhua948** [IBM-Swift/BlueSocket#105]
What I am doing:
```swift
var socket = Socket.create()
socket.connect(...)
socket.write(string)
let ret = socket.read(into: &data) // This lines throws the error: Error code: -9982(0x-26FE), Interrupted system call
```

Added a `sleep(1)` after line 1 seems to resolve this issue, any idea why is this the case?
OS: MacOS
Swift: 4.0

**Comment by qhua948** [comment]
I tracked down the issue, it is from line 3452 of `Socket.swift`
```swift
count = Darwin.recv(self.socketfd, self.readBuffer, self.readBufferSize, recvFlags)
```

**Comment by billabt** [comment]
Can you tell me which _flavor_ of **connect()** you're using?  Also, a check of _socket.isConnected_ would be useful after the connect to ensure that you're actually connected to the server.  Finally, you should check to ensure that the socket is _writable_ before attempting to write to it.  You can use the instance function _isReadableOrWritable(waitForever: Bool = false, timeout: UInt = 0)_ to check for writability.

**Comment by qhua948** [comment]
Thanks for the response.

I was using `connect(host:port)` and I was checking for `isConnected` before using it.
But checking whether the socket it read/writable solves the problem in my case, perhaps this could be stated in the document more clearly?

**Comment by billabt** [comment]
I'll look at adding some info to the documentation.  Thanks.
