### ISSUE TITLE
iOS: Does streaming audio / video supported by Bluesocket?

### ISSUE THREAD

**Issue by parvezq** [IBM-Swift/BlueSocket#106]
Is it possible to stream audio / video from camera/microphone using BlueSocket on iOS? What I want to accomplish is to have an audio / video chat session using built in audio / video api from iOS (AVFoundation) along with BlueSocket. Any code snippet/ suggestion will be greatly helpful.
Thanks

**Comment by billabt** [comment]
Theoretically, yes.  You should be able to use the _AVCapture_ APIs to capture the video from the camera/microphone and then use _BlueSocket_ to stream it out.  However, streaming it efficiently is going to depend on a lot of things.  _BlueSocket_ is simply a transport layer.  You'll have to worry about compressing and packetizing the data you get from the _AVCapture_ API **before** you transmit it using _BlueSocket_.  Then, correspondingly, you'll have to decode the packets and decompress the data back into a usable form for subsequent display and playback.  I've done this before in Objective-C in the proprietary world and (not trying to discourage you) it's a rather daunting task to get it right.  Hope this helps.  Feel free to re-open the issue if you have anymore questions.

**Comment by parvezq** [comment]
Hi, 
1. We have connected 2 iOS devices with BlueSockets API. 
2. We are simultaneously doing 2 things:
	1. capturing mic audio and writing it to socket.
	2. reading data and playing received audio buffer using AVAudioEngine.
3. For both the steps we are using AVAudioEngine class.
4. But we are not able to record and play it in any way.

I am also sharing my code snippet and wish to ask if you can tell any potential problem with my code.

Snippet for setting up AudioEngine:
```
func connect() {
		do {
			try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, with: [.defaultToSpeaker])
			try AVAudioSession.sharedInstance().setActive(true)
			try AVAudioSession.sharedInstance().setMode(AVAudioSessionModeVoiceChat)
			AVAudioSession.sharedInstance().requestRecordPermission({ (flag) in
				
			})
		}
		catch {
			print(error)
		}
		
		let inNode = remoteAudioEngine.inputNode
		
		let mixer = localAudioEngine.mainMixerNode
		
		localAudioEngine.attach(localAudioPlayer)
		remoteAudioEngine.attach(remoteMainMixer)
		
		remoteAudioEngine.connect(inNode, to: remoteMainMixer, format: format)
		
		localAudioEngine.connect(localAudioPlayer, to: mixer, format: format)
		localAudioEngine.connect(mixer, to: localAudioEngine.outputNode, format: format)
		
		serialQueue.async {
			
			#if Server
				self.remoteMainMixer.installTap(onBus: 0, bufferSize: 4096, format: self.format) { (buffer, time) in
					do {
						let data = AudioConverterHelper.audioBufferToData(audioBuffer: buffer)
						//let nsdata = Data(bytes: data)
						let len = try (self.socketManager?.connectedSockets.first?.write(from: data))
						print(len)
					}
					catch { print(error) }
				}
			#elseif Client
				
				self.remoteMainMixer.installTap(onBus: 0, bufferSize: 4096, format: self.format) { (buffer, time) in
					do {
						let data = AudioConverterHelper.audioBufferToData(audioBuffer: buffer)
						//let nsdata = Data(bytes: data)
						let len = try self.clientSocketManager?.socket?.write(from: data)
						print(len)
					} catch { print(error) }
				}
			#endif
		}
		
		do {
			localAudioEngine.prepare()
			
			try localAudioEngine.start()
		} catch { print(error) }
		do {
			remoteAudioEngine.prepare()
			
			try remoteAudioEngine.start()
		} catch { print(error) }
		
	}

Snippet for playing audio buffer: 
func setupAndPlay(data: Data) {
		var buffer = AudioConverterHelper.dataToAudioBuffer(data: data)
		localAudioPlayer.scheduleBuffer(buffer, completionHandler: nil)
		localAudioPlayer.play()
	}
```

We are not able to regenerate audio sound as received from socket, in the method setupandplay().
Please share your views on the above code.

**Comment by zchacker** [comment]
Hi @parvezq  how are you?
does AVFoundation support playing audio from stream? what about Audio Queue Services?
