### ISSUE TITLE
How to connect to hostname:port on a specific path (web socket stream)?

### ISSUE THREAD

**Issue by sdrpa** [IBM-Swift/BlueSocket#108]
I'd like to connect to eg.
wss://stream.binance.com:9443/ws/ethbtc@kline_1m

```
...
let signature = try Socket.Signature(protocolFamily: .inet, socketType: .stream, proto: .tcp, hostname: "wss://stream.binance.com/ws/ethbtc@kline_1m", port: Int32(9443))
self.socket = try Socket.create(connectedUsing: signature!)
...
```

I get `SOCKET_ERR_GETADDRINFO_FAILED` error. I can connect if I provide only`wss://stream.binance.com` as hostname, but I also need to specify the path (/ws/ethbtc@kline_1m).
Could you help how to specify host and path separately, can't find correct initializer...

**Comment by billabt** [comment]
I think that you're thinking more along the lines of _URLSession_ which is at a higher level than sockets.  The _BlueSocket_ API supports _low level_ socket access.  Try looking at the documentation for _URLSession_.  I think you'll find that that better suits your needs.  If you have any questions, feel free to re-open this issue.  Good luck.
