### ISSUE TITLE
listen(forMessage data: inout Data, on port: Int, maxBacklogSize: Int = Socket.SOCKET_DEFAULT_MAX_BACKLOG)

### ISSUE THREAD

**Issue by cloeffler** [IBM-Swift/BlueSocket#109]
hello, i am trying to send a receive data over udp. And i am able to send just fine using the write function. But when i try to use the listen function above i keep getting "invalid argument". If its not too much trouble could someone give  me an example of using this listen function, and the init of all of the arguments. I think im creating  my Data object wrong or something

**Comment by billabt** [comment]
Take a look at the _testListenUDP()_ function in **SocketTests.swift**.  That should give you a good idea of how to call the function.  Re-open if you need further assistance.

**Comment by cloeffler** [comment]
thanks bill, ill try that

**Comment by cloeffler** [comment]
hey bill, still not getting it. it seems like my udp port is listening but no data is coming in. Would you   happen to know if there is something on IOS you need to do in order to open the port? Or should this code be sufficient to open the port and start receiving.  
here is the code i am using at the moment

` func testListenUDP() {



        let queue: DispatchQueue? = DispatchQueue.global(qos: .userInteractive)

        guard let pQueue = queue else {



            print("Unable to access global interactive QOS queue")



            return

        }



        do {



            // Create the socket..

            let socket = try Socket.create(family: .inet, type: .datagram, proto: .udp)



            pQueue.async { [unowned self, socket] in



                do {

                    // Listen on the port...

                    var data = Data()

                    print("listening")

                    _ = try socket.listen(forMessage: &data, on: Int(4055))

                    print("listening")

                } catch let error {



                    // See if it's a socket error or something else...

                    guard let socketError = error as? Socket.Error else {



                        print("Unexpected error...")



                        return

                    }



                    if socketError.errorCode != Int32(Socket.SOCKET_ERR_RECV_FAILED) {

                        print("testListenUDP Error reported: \(socketError.description)")



                    }

                }

            }



            // Give the thread time to start...

            #if os(Linux)

                _ = Glibc.sleep(1)

            #else

                _ = Darwin.sleep(1)

            #endif







            // Close the socket...

            socket.close()





        } catch let error {



            // See if it's a socket error or something else...

            guard let socketError = error as? Socket.Error else {



                print("Unexpected error...")



                return

            }



            print("testListenUDP Error reported: \(socketError.description)")



        }

    }`

**Comment by billabt** [comment]
What's on the other side of the UDP connection?  Is it your own server?  Is it always transmitting?  The code above **closes** the socket after waiting for the thread to start.  So, you're definitely not going to get any data that way...  The test function I pointed you too simply tests the functionality of that function.  You'll need different logic and more infrastructure.

**Comment by cloeffler** [comment]
on the other side  i have a udp packet sending utility that sends continuously. But in the code above you see where i have put the print statments "listening",  by doing that i found that the code never moves past the socket.listen part of the code, so the socket never gets closed it just stays at socket.listen. In reallity ill i need to do is receive 1 message and then close the socket.

**Comment by billabt** [comment]
I’m trying to reproduce this and would like to know what UDP packet sending utility you’re using along with the contents of the packet you’re sending. Thanks.

**Comment by cloeffler** [comment]
hey, here is the utility,
https://packetsender.com/


and the contents of the packet is   "hello from pc"
 to port 4055, <iphone ip>
udp

**Comment by daihieptn97** [comment]
Hope it can help you
```switf
    func testListenUDP() {
        let queue: DispatchQueue? = DispatchQueue.global(qos: .userInteractive)
        guard let pQueue = queue else {
            print("Unable to access global interactive QOS queue")
            return
        }
        do {
            // Create the socket..
            
            let socket: Socket = try Socket.create(family: .inet, type: .datagram, proto: .udp)
            //             try socket.connect(to: "127.0.0.1", port: Int32(1111))
            
            pQueue.async { [unowned self, socket] in
                do {
                    // Listen on the port...
                    var data = Data()
                    print("listening ... ")
                    _ = try socket.listen(forMessage: &data, on: Int(1111))

                    print("Accepted connection from: \(socket.remoteHostname) on port \(socket.remotePort), Secure? \(socket.signature!.isSecure)")
                   
                    guard let dataResut =  NSString(data:  data, encoding: String.Encoding.utf8.rawValue) else {
                        print("Error decoding response...")
//                        readData.length = 0
                        return
                    }
                    print(dataResut)
                    socket.close()
                    print("socket close")
                } catch let error {
                    
                    // See if it's a socket error or something else...
                    guard let socketError = error as? Socket.Error else {
                        socket.close()
                        print("socket close")
                        print("Unexpected error...")
                        return
                    }
                    if socketError.errorCode != Int32(Socket.SOCKET_ERR_RECV_FAILED) {
                        socket.close()
                        print("socket close")
                        
                        print("testListenUDP Error reported 1: \(socketError.description)")
                    }
                }
            }
            
            
        } catch let error {
            // See if it's a socket error or something else...
            guard let socketError = error as? Socket.Error else {
                print("Unexpected error...")
                return
            }
            print("testListenUDP Error reported: \(socketError.description)")
            
        }
        
        
    }
