### ISSUE TITLE
How get the broadcast bound local port?

### ISSUE THREAD

**Issue by alessandro308** [IBM-Swift/BlueSocket#112]
I'm trying to explain what problem I have. I need to broadcast a message and then, a device in a network, reply to me using the same address (IP:port) from where the broadcast message was sent. 
In detail, I'm implementing the discovery protocol described [here](http://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf) for Xiaomi Yeelight Smart Bulb.

There a way to know which is the port that has sent the broadcast message in order to listen to it for incoming message?

**Comment by billabt** [comment]
When you receive a broadcast message, an **Address** is returned that contains info you're looking for.  You can use the _class function_ **Socket.hostNameAndPort(from:)** by passing in the **Address** that you got back when you received the message.

Take a look at the function _udpHelper()_ in **SocketTests.swift** for a usage example...

I'm going to close this for now. Re-open if you have any questions. Thanks.
