### ISSUE TITLE
Put deployment target back to 9?

### ISSUE THREAD

**Issue by o2x7** [IBM-Swift/BlueSocket#113]
We still need to support ios9.  I have moved the deployment target back to 9 in a branch and it appears to work fine.  Is there some reason this needs to be bumped up to 10 and is there any way we could leave it as compatable as possible?

**Comment by o2x7** [comment]
Pull req here: https://github.com/IBM-Swift/BlueSocket/pull/114

**Comment by billabt** [comment]
There's no issue with _BlueSocket_ using iOS 9 for a deployment target.  However, the SSL/TLS add-on for it, _BlueSSLService_, requires iOS 10 or higher.  Having them at different deployment targets causes issues when attempting to build a project that includes both.  Hence the change.  Keeping both at the _minimal target required for both_ of them eliminates a lot of confusion.

**Comment by mcfedr** [comment]
I'm actually using both BlueSocket and BlueSSLService on iOS 9.3 with no issues. I'd really like to make a PR to both projects with change to iOS 9 target if @billabt would be open to it.

**Comment by billabt** [comment]
I’ll do some testing here and if it work out, I’ll make the change. Reopening so I don’t forget. 😉

**Comment by mcfedr** [comment]
I've been using myself:
https://github.com/IBM-Swift/BlueSocket/compare/master...mcfedr:signature-ios9
https://github.com/IBM-Swift/BlueSSLService/compare/master...mcfedr:ios9

**Comment by billabt** [comment]
Is this still needed?

**Comment by billabt** [comment]
Apparently _not_.  😉
