### ISSUE TITLE
How to read long strings

### ISSUE THREAD

**Issue by andybiar** [IBM-Swift/BlueSocket#117]
Hey all,

I'm using this library (version 0.12.78) to send and receive some JSON Strings of 3000+ characters including escaped quotations ( \"  ) and escaped backslashes ( \\ ). I won't post my schema but I can probably generate another sample String if needed.

When I call `socket.write(from: String)` with a TCP ipv4 socket on one of these longer JSON Strings and read it on the other end, the received result is always incorrectly truncated before the end of the string. Using `socket.write(from: Data)`, however, with `stringvar.data(using: String.Encoding.utf8)` works like a charm.

Any idea what's going on here? Looks like the culprit is `string.utf8CString.withUnsafeBufferPointer()` on line 3011 of Socket.swift in this version. Could be a Swift 4 bug? I'm seeing Swift 4 documentation using string.utf8 instead of utf8CString?

https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/StringsAndCharacters.html

**Comment by billabt** [comment]
I’ll take a look. If you could post a string that illustrates the problem, that’d be really helpful. Thanks.

**Comment by andybiar** [comment]
I've been working on this a little more, and I think I was mistaken before. It looks like regardless of the buffer size of string, Data, or NSData, Darwin can choose how many send commands are required to send (Hence your loop on `write(from buffer`..)). My solution above doesn't work 100% of the time.

So now I'm left with what should be a pretty easy question.. Is there an elegant way to tell on the receiving end whether I have received the entire message or whether another send call is coming?

**Comment by billabt** [comment]
Use the _isReadableOrWritable()_ instance function to see if the Socket has data to be read.

**Comment by andybiar** [comment]
Ahh ok. I wasn't clear on the definition of readable or writable before, but that makes sense. Tested and resolved, will close issue. Thanks.

**Comment by andybiar** [comment]
Hey Bill,

Sorry to bother you again, but some issues came up that I can't attribute to anything other than unexpected behavior in `isReadableOrWritable()` at this time. My run loop looks like this on a tcp socket in Swift 4; is this the intended usage of isReadableOrWritable()?

Right now my observed behavior is that I'm seeing the first 1MB of my long string come in, and `isReadableOrWritable().readable` returns false even though the string is incomplete. I print the incomplete string to verify, and then fail the JSON parse.

```
var receivedData: Data? = Data(capacity: 32768)
do { repeat { 
    let bytes = try socket.read(into: &receivedData!)  
    if bytes == 0 { _<check for shutdown condition>_ }             
    let msgIsIncomplete = (try socket.isReadableOrWritable().readable)
    if msgIsIncomplete {
        self.log.info("Received \(bytes) bytes but message is incomplete. Reading again.")
        continue
    }
    // message is assumed to be valid at this point
    let message = String(data: receivedData!, encoding: .utf8)!
    print(message)
    parseJSON(message)
} // while not shutdown condition
```

Right now I'm working around this by adding my own custom message termination string and checking all inputs for the termination string, but this seems like something the framework should handle for me as you said above? Wondering if anyone else has seen this or if I'm not correctly implementing the check

**Comment by billabt** [comment]
Your check looks fine.  It'd be interesting to see the other side.  Is that also using _BlueSocket_?  So far, I've been unable to reproduce the problem.  I'm using your code as above but without knowing how the other side is sending, it's hard to reproduce your exact scenario.

**Comment by andybiar** [comment]
The other side is also using BlueSocket, a simple `try socket.write(from: longString)`. I'll look to get a playground running where I can reproduce the bug and post a link here, likely next week.

**Comment by billabt** [comment]
Thanks Andy.

**Comment by rtabassum11** [comment]
i m trying to write long string, it producing error saying long massage, anyone can give me a simple example?

**Comment by billabt** [comment]
Please re-open this issue if still a problem...

**Comment by ShaunMurph** [comment]
> Hey Bill,
> 
> Sorry to bother you again, but some issues came up that I can't attribute to anything other than unexpected behavior in `isReadableOrWritable()` at this time. My run loop looks like this on a tcp socket in Swift 4; is this the intended usage of `isReadableOrWritable()`?
> 
> Right now my observed behavior is that I'm seeing the first 1MB of my long string come in, and `isReadableOrWritable().readable` returns false even though the string is incomplete, so there is data yet to be read (expected: true). I print the incomplete string to verify, and then fail the JSON parse.
> 
> ```
> var receivedData: Data? = Data(capacity: 32768)
> do { repeat { 
>     let bytes = try socket.read(into: &receivedData!)  
>     if bytes == 0 { <check for shutdown condition> }             
>     let msgIsIncomplete = (try socket.isReadableOrWritable().readable)
>     if msgIsIncomplete {
>         self.log.info("Received \(bytes) bytes but message is incomplete. Reading again.")
>         continue
>     }
>     // message is assumed to be valid at this point
>     let message = String(data: receivedData!, encoding: .utf8)!
>     print(message)
>     parseJSON(message)
> } // while not shutdown condition 
> }
> ```
> 
> Right now I'm working around this by adding my own custom message termination string and checking all inputs for the termination string, but this seems like something the framework should handle for me as you said above? Wondering if anyone else has seen this or if I'm not correctly implementing the check of `isReadableOrWritable()`?

We can use alternate of isReadableOrWritable().

Code:

//1-Main function
func readStringFromServer()->String?{        
        var jsonString = ""
        	guard let readData = NSMutableData(capacity:32768) else {return nil}
        var shouldKeepRunning = true        
        repeat{
            do {
                let bytesRead = try socket.read(into: readData)                
                if bytesRead == 0 {
                    shouldKeepRunning = false
                }                
                if let str = NSString(bytes: readData.bytes, length: readData.length, encoding: String.Encoding.utf8.rawValue),
                        bytesRead > 0{
                    jsonString.append(str as String)                    
                    if msgIsIncomplete(str: jsonString){
                        print("Received \(bytesRead) bytes but message is incomplete. Reading again.")
                        jsonString.removeAll()
                        continue
                    }
                    else{
                        shouldKeepRunning = false
                    }
                }
                else{
                    shouldKeepRunning = false
                }
                readData.length = 0                
            }catch {              
                print("localizedDescription== \(error.localizedDescription)")
                shouldKeepRunning = false
            }            
        } while shouldKeepRunning      
        return jsonString
}


//2-Helper function
func msgIsIncomplete(str:String)->Bool{
        let openCount = str.numberOfOccurrences("{")
        let closeCount = str.numberOfOccurrences("}")
        if openCount > 0 || closeCount > 0{
            if openCount != closeCount{
                return true
            }
        }
        return false
    }

// 3 -Helper function
extension String {    
    public func numberOfOccurrences(_ string: String) -> Int {
        return components(separatedBy: string).count - 1
    }    
}


Note : We can check the message is incomplete via call msgIsIncomplete(str:String) function and  goto read again if it return true otherwise message is complete.

**Comment by andybiar** [comment]
Hey Sean,

This is the behavior I saw last year. I ended up just going into production
checking for my own termination string.
