### ISSUE TITLE
InputStream and OutputStream?

### ISSUE THREAD

**Issue by zzhao36** [IBM-Swift/BlueSocket#122]
Hi Bill,
    This is a really great library, thanks so much for sharing it! I'm a student trying to learn more about socket programming. My question is about simultaneous reading and writing of data. In iOS we have 
InputStream and OutputStream. If I wanted to replicate that type of two way communication, would I 
have to create two sockets to every device I wanted to connect to? Or is there some way I can achieve reading and writing on a single socket? Thanks!

**Comment by billabt** [comment]
Thanks for compliments, much appreciated. InputStream and OutputStream are basically _wrappers_, each on top of low level socket. Therefore, in order to achieve that type of functionality, you need to create two sockets, one for reading and one for writing ideally on separate dispatch threads. This will allow you to do simultaneous communication. Hope this helps. If you anymore questions, feel free to reopen the issue.

**Comment by zzhao36** [comment]
Hi Bill,
Thank you for the fast reply. I'm playing around with your EchoServer code, and trying to adapt it so it can run on iOS devices. One concern I have is when the user will background the application or put the iOS device to sleep. Is there a way for me to set "shouldKeepRunning" to false even when the thread is blocked at "socket.read"? Maybe there is a clever way to do it, ie send the socket a "quit" command? Please let me know if you don't understand what I'm asking. Thanks!

```
repeat {
    let bytesRead = try socket.read(into: &readData)
    if bytesRead > 0 {
        guard let response = String(data: readData, encoding: .utf8) else {
            print("Error decoding response...")
            readData.count = 0
            break
        }
        print("Server received from connection at \(socket.remoteHostname):\(socket.remotePort): \(response) ")
        let reply = "Server response: \n\(response)\n"
        try socket.write(from: reply)
        
        if response.hasPrefix(EchoServer.quitCommand) || response.hasSuffix(EchoServer.quitCommand) {
            shouldKeepRunning = false
        }
    }
    
    if bytesRead == 0 {
        shouldKeepRunning = false
        break
    }
    readData.count = 0
} while shouldKeepRunning
```
