### ISSUE TITLE
Find UDP source port

### ISSUE THREAD

**Issue by igorsquadra** [IBM-Swift/BlueSocket#124]
Hello Bill,
first of all thank you for your work, that's amazing.
I'm trying to retrieve the source port while I'm listening data from a specific destination port.
I already know the ip and destination port but I didn't find a way to retrieve the source port.
Hope I was clear, thank you in advance.

**Comment by billabt** [comment]
Are you looking for the local port the message came in on?

**Comment by igorsquadra** [comment]
Basically my hardware has a WiFi module connected via serial port. The WiFi module send messages from its own source port to the port 123 (for example). The port 123 is the destination port, but I need to know the source port from where the message has been sent.

**Comment by billabt** [comment]
Can you post a little code snippet so I can see what APIs that you're using?  Also, if I don't respond for a little bit it's not because I forgot about it.  I just had some surgery and am still in _recovery mode_ so I'm not checking this as frequently as I normally do...

**Comment by billabt** [comment]
I was just thinking...  Did you try using the _class function_ **Socket.hostNameAndPort(from:)** by passing in the **Address** that you get back when you read the message?  That should do it.  I completely forgot about that function. 🤪

I'm going to close this for now.  Re-open if you have any questions.  Thanks.
