### ISSUE TITLE
nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by shinma** [IBM-Swift/BlueSocket#129]
iOS: 11.3
Xcode: 9.3

When: on executing connect(to host: String, port: Int32, timeout: UInt = default) on Socket
Possible cause: getaddrinfo()

**Comment by shinma** [comment]
.create(family: .**inet6**, type: .stream, proto: .tcp)

**Comment by shinma** [comment]
Even though I'm not using IP address it shouldn't work like this. What if provider switches to IPv6 in the meantime.

**Comment by billabt** [comment]
I've made a change to the signature of the _connect()_ function that corrects the problems but also allows for the caller to specify that only a socket of the family of the calling _Socket_ will be allowed.  The default is to allow connection to a socket of any family.  This change will be in the latest version, _1.0.2_, as soon as I get it posted.  Thanks.

**Comment by davidjaystrauss** [comment]
What was the fix on this? I'm still having this error occur on socket create in 1.0.46

**Comment by billabt** [comment]
@davidjaystrauss What error are you getting?  Can you give me an example of the code?  Thanks.

**Comment by davidjaystrauss** [comment]
Hi @billabt, definitely!

We aren't specifying anything to the create method, as we're using this in parallel with BlueSSLService.

So for create we just call `try Socket.create()` and get `Error code: -9989(0x-2705), nodename nor servname provided, or not known`

**Comment by davidjaystrauss** [comment]
Some more info:

After creation we specify host/port with `try socket.connect(to: self.config.getProxyHost(), port: Int32(self.config.getProxyPort()))`

**Comment by billabt** [comment]
What is the value being returned by _self.config.getProxyHost()_?  The error you're getting indicates a _getaddrinfo()_ failure...
