### ISSUE TITLE
Operation not permitted when trying to connect to a socket

### ISSUE THREAD

**Issue by Tymolc** [IBM-Swift/BlueSocket#133]
I am trying to connect to a local socket like so:

```
var _socket: Socket? = nil
_socket = try! Socket.create(family: Socket.ProtocolFamily.unix, proto: Socket.SocketProtocol.unix)
let socketPath = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.identifier")!
                 .appendingPathComponent("name").path
_socket.connect(to: socketPath)
```

However, I always get an error `'Error code: -9988(0x-2704), Operation not permitted'`

I tried the suggestion in another ticket to check "Outgoing Connections" in the Xcode permissions and am not sure what to do anymore. The same code works on another machine. Are there some other Xcode settings I am missing?

**Comment by billabt** [comment]
Let me see if I can reproduce the problem.  If you've got a complete test case that illustrates the problem and you can post it, that'd speed things up.  Thanks.

**Comment by Tymolc** [comment]
Sorry, I hope you didn't put too much time into this. My problem was, that I wanted to access a unix socket in a Group Container folder, but I didn't give my Xcode app the permission to access this app group. After I added the folder name to the app groups, it worked.
