### ISSUE TITLE
Echo Server with GUI

### ISSUE THREAD

**Issue by AliJalil** [IBM-Swift/BlueSocket#136]
I use BlueSocket and create an EchoServer class in iOS, it's worked correctly but I need to use it with an interface, when I create an object of echoServer it's prevent GUI from responding, How can I resolve that?

**Comment by billabt** [comment]
To fix this, you need to move code that's listening on the socket off the main (i.e. UI) thread.

**Comment by AliJalil** [comment]
Can you provide me a code to do that?
