### ISSUE TITLE
Invalid test module name

### ISSUE THREAD

**Issue by TheSoundDefense** [IBM-Swift/BlueSocket#14]
During our automated builds of the newest Swift snapshots for the Sandbox, we run into the following issue while incorporating BlueSocket:

```
swift-build: error: the module at Tests/Socket has an invalid name ('Socket'): the name of a test module has no 'Tests' suffix
fix: rename the module at 'Tests/Socket' to have a 'Tests' suffix
```

This began with the 7-29 snapshot a week ago. Sounds like a quick fix?

**Comment by rfdickerson** [comment]
Hey Jim- you need to use his master-next branch. Since 7/29 has broken Tests, Bill hasn't upgraded yet.

**Comment by TheSoundDefense** [comment]
Thanks for the heads up, I'll change our automation.

**Comment by billabt** [comment]
I'll hopefully be upgrading either over the weekend or Tuesday when I get back to work. The master-next branch is 7/29 compatible with the exception of tests on Linux.
