### ISSUE TITLE
Set read timeout doesn't work

### ISSUE THREAD

**Issue by Rickrk** [IBM-Swift/BlueSocket#141]
After setting socket timeout to `10000` using `setReadTimeout` method, when I run the application and it waits for the server's response, it will wait until I activate or deactivate breakpoints!!!!
![screenshot from 2018-06-27 17-21-51](https://user-images.githubusercontent.com/30596240/41975050-e51e3dae-7a2e-11e8-9ddc-540a3f5c2eb2.png)

So `setReadTimeout` method do nothing.
 
It's a strange behaviour that Xcode shows. Can the problem be related to `BlueSocket` code or it can be Xcode bug?

**Comment by billabt** [comment]
Timeouts don't typically work in Xcode.  This has been a problem for a _very long_ time.  As far as the _setReadTimeout()_ function, that is working as it's supposed to.  This is the way the underlying BSD socket system works.  Take a look at the _SocketTests.swift_ methods that test the timeouts for example code.  Re-open if you have any more questions...
