### ISSUE TITLE
LICENSE file still a template, doesn't contain copyright line

### ISSUE THREAD

**Issue by jaden-young** [IBM-Swift/BlueSocket#142]
Source files have copyright IBM, but the LICENSE file at the root of the project has neither year nor copyright holder.

https://github.com/IBM-Swift/BlueSocket/blob/e2f6aee81b9e316f61e173e8350cb69d7714ead8/LICENSE#L189

**Comment by billabt** [comment]
The LICENSE file at the root of the project contains the Apache License...  Closing this issue as **not valid**.

**Comment by jaden-young** [comment]
@billabt Sorry if I failed to communicate the issue clearly. The issue is that the license at the root of the project contains the Apache license **TEMPLATE**. It is not complete. According to the [Apache documentation](http://www.apache.org/licenses/LICENSE-2.0.html#apply), the line with "Copyright {yyyy} {name of copyright owner}" should be replaced with "Copyright 2016 IBM".

See the difference between what exists in the source files:
https://github.com/IBM-Swift/BlueSocket/blob/e2f6aee81b9e316f61e173e8350cb69d7714ead8/Sources/Socket/Socket.swift#L6

and what exists in the current template at the root of the project:
https://github.com/IBM-Swift/BlueSocket/blob/7061bd13ed7bf2292283e542287cdcb2cb71ad01/LICENSE#L189

A tangible benefit to this change is enabling use with tools such as https://github.com/mono0926/LicensePlist that integrate with Carthage/Cocoa pods to automatically include the LICENSE file as an acknowledgement in projects that use the library.

**Comment by billabt** [comment]
Fixed them ALL.  The other Blue* were missing it too.  Thanks.
