### ISSUE TITLE
CocoaPods import BlueSocket Error

### ISSUE THREAD

**Issue by Crazyya** [IBM-Swift/BlueSocket#146]
<img width="1536" alt="bluesocketerror" src="https://user-images.githubusercontent.com/11494538/44332666-227a5d00-a49f-11e8-9747-6e8d9571ba68.png">
I am reporting an error when referring to BlueSocket:

Binary operator '|' cannot be applied to operands of type '__int32_t' (aka 'Int32') and 'Int'

Can you tell me what to do, thanks

**Comment by billabt** [comment]
Can you give me some more info?  Swift version, Xcode version, macOS version?  Maybe a small example illustrating the problem.  It builds fine here in my tests.

**Comment by Crazyya** [comment]
Sorry, I have no problem with creating a new project reference. It should be caused by my previous project. I will check the reason myself, thank you!

**Comment by jifang** [comment]
I was having the same issue by accidentally set the pod iOS platform to 8.0. Change it to 10.0 will fix this problem
