### ISSUE TITLE
Not safe for use in application extensions

### ISSUE THREAD

**Issue by MaxiHuHe04** [IBM-Swift/BlueSocket#148]
I have an iOS app with an application extension (Share) where I need sockets. When I build the project with BlueSocket, XCode gives me a warning:
```
ld: warning: linking against a dylib which is not safe for use in application extensions: /.../Socket.framework/Socket
```

**Comment by billabt** [comment]
Check out this thread —> https://bugzilla.mozilla.org/show_bug.cgi?id=1127505

That should help you. If not reopen the issue.
