### ISSUE TITLE
Socket.createAddress returning ipv6 address for ipv4 address

### ISSUE THREAD

**Issue by ssokol** [IBM-Swift/BlueSocket#155]
This is a weird issue. I'm running iOS 12.1 on several devices, including a brand new 11" iPad Pro. On all of the hardware except for the Pro, the Socket.createAddress() method properly returns an ipv4 address. On the Pro, for some reason, calls to Socket.createAddress() with a broadcast address (in this case, 192.168.10.255) are being mis-recognized by the getaddrinfo() function as v6.

Any thoughts?

**Comment by ssokol** [comment]
This may turn out to be a bug in the iOS networking stack. See:

https://forums.developer.apple.com/thread/111661

**Comment by billabt** [comment]
Can you try something?  Remove the SIM card from the iPad Pro and then try it again...  I'd _almost_ bet money that it'll work the way you expect.  Let me know.  Thanks.

**Comment by ssokol** [comment]
You are correct sir! As soon as I remove the SIM and restart the app, the getaddrinfo function works as expected and treats the value as IPv4. I'm working this with the support team at Apple, so I think you can close this.

Thanks! -S
