### ISSUE TITLE
"Address already in use" when handing off from NetService

### ISSUE THREAD

**Issue by robreuss** [IBM-Swift/BlueSocket#157]
I'm running NetService with the listenForConnections option and port set to 0 when publishing, so a port is automatically selected.  When I try to listen on a socket with the assigned port, I get an "Address already in use" error.  In contrast, if I don't have the listenForConnections option on NetService and specify a port, everything works fine.  Any thoughts on how I can resolve this quandary?

**Comment by billabt** [comment]
I'm not that familiar with NetService but it sounds like it's not setting SO_REUSEPORT on the socket it's listening on.  You might want to check an' see if that's an option.  Also make sure that when you call the _listen_ API, you set _allowPortReuse = true_.

**Comment by robreuss** [comment]
I found the cause it was fairly obvious.  I was passing 0 for a port to NetService to obtain an automatically assigned, but when I reached the stage of starting up the BlueSocket listener, the port was still being report as 0.  I assume port 0 is already in use, so no wonder BlueSocket complains!  Now I need to figure out why I'm not getting a newly assigned port from NetService.  Thank you sir!
