### ISSUE TITLE
Unable to convert data to NSString

### ISSUE THREAD

**Issue by PY4OG** [IBM-Swift/BlueSocket#166]
Error code: -9974(0x-26F6), Unable to convert data to NSString
how to fix it!  - swift 4.2.1 Mac Os 
```
func readSpot() {
    do {
        repeat {          
            if let result = try spotSocket?.readString() {
                print(result)
             //...code
            }
        }  while continueRunning
    }  catch let error {
        print("Unexpected error... \(error)")  // Error code: -9974(0x-26F6), Unable to convert data to NSString
    }
}
```

**Comment by JanX2** [comment]
There is to enough information here to give a detailed answer. 

The data sent by the server you are connecting to is probably not valid UTF8. Try reading as `Data` and validating that to see where on the server the issue might be coming from.

**Comment by PY4OG** [comment]
Thanks @JanX2 . Is a way! Some idea to filter non-valid utf8 before converting to NSString.

**Comment by JanX2** [comment]
@PY4OG Fix your server. If something doesn’t use valid UTF8 then it should be fixed ASAP. :)

**Comment by PY4OG** [comment]
thanks again @JanX2!   I understand, but in this case it is a large telnet network with many nodes and different server applications, running in hundreds of countries. I have no control over these servers. It work without problem in telnet cmd. I have to fix it on the iOS client. At moment I filter one line after catch, need to filter just not-valid utf8.

**Comment by JanX2** [comment]
Non-valid utf8 is just this: not UTF8 at all. If it’s a regular issue, I would recommend looking for something that cleans your input to be valid. Swift’s `String.decodeCString()` seems to fit the bill (untested).

**Comment by PY4OG** [comment]
I will try! Thanks
