### ISSUE TITLE
Outdated README

### ISSUE THREAD

**Issue by charlag** [IBM-Swift/BlueSocket#17]
First example in README now looks like this
```
var socket = try Socket.create()
guard let socket = socket else {
  fatalError("Could not create socket.")
}
try socket.listen(on: 1337)
```

While it should look like this
```
var socket = try Socket.create()  
try socket.listen(on: 1337)
```

**Comment by billabt** [comment]
You're absolutely right. I'll make the change. Thanks for pointing this out.

**Comment by charlag** [comment]
Thank you!
Sorry for not making a pull request, I was just unsure how to do it properly.
