### ISSUE TITLE
Swift 5.0 Build  failed

### ISSUE THREAD

**Issue by dengfeng520** [IBM-Swift/BlueSocket#174]
I imported my project through cocoapods，Swift 5.0 Build Swift  failed.
Wrong on line 750 of the Scoket.swift file,

```
readBuffer.deinitialize()
readBuffer.deallocate(capacity: oldValue)
readBuffer = UnsafeMutablePointer<CChar>.allocate(capacity: readBufferSize)
readBuffer.initialize(to:0)
```
How can I solve these problems, thx.

**Comment by billabt** [comment]
It looks like you're using an **old** version of _BlueSocket_.  Can you provide a bit more information?  Maybe a build trace or log?  Thanks.

**Comment by dengfeng520** [comment]
Thanks for your reply.
I am using the **BlueSocket** version **(1.0.46)**. This is the latest version of CocoaPods.

**Comment by billabt** [comment]
I haven't been able to reproduce the problem here.  The other thing is that _line 750 in Socket.swift_ on my source shows the following code:
```
		///
		/// Returns a string description of the error. (Readonly)
		///
		public var description: String {

			let reason: String = self.errorReason ?? "Reason: Unavailable"
			return "Error code: \(self.errorCode)(0x\(String(self.errorCode, radix: 16, uppercase: true))), \(reason)"
		}   <---- THIS IS LINE 750.
```
Can you send me your build trace?  Thanks.

**Comment by dengfeng520** [comment]
Thanks for your reply.
I upgraded**CocoaPods** and the build was successful.
