### ISSUE TITLE
Binary operator '&' cannot be applied to operands of type '__int32_t' (aka 'Int32') and 'Int'

### ISSUE THREAD

**Issue by akshit5230** [IBM-Swift/BlueSocket#178]
Swift 4.2 Xcode 10.3

**Comment by billabt** [comment]
Unable to reproduce.  Currently passing CI without problem using Swift 4.2.1.  Can you provide anymore info?  Thanks.

**Comment by akshit5230** [comment]
I installed this library via CocoaPods. When i tried to build it game 108 errors. They were from some utils file where 'mask' was written and Xcode was saying to convert it to Int32. Then somehow I was able to resolve all of them but then When I tried to create a UDP Socket server it didn't work.

**Comment by billabt** [comment]
Were you able to resolve the problem?  Thanks.
