### ISSUE TITLE
Cannot find out which port was assigned

### ISSUE THREAD

**Issue by Bouke** [IBM-Swift/BlueSocket#22]
Sometimes you don't want to listen on a prespecified port, but just a port number assigned by the OS. In C you'd listen on port 0. To find out which port was assigned after listening, you'd call ``getsockname`` and lookup the ``sa(6)_port`` attribute. However it appears that this currently isn't implemented in BlueSocket.

**Comment by billabt** [comment]
This is fixed in the latest release.  Thanks for the heads-up.
