### ISSUE TITLE
Unable to 'import Socket'

### ISSUE THREAD

**Issue by jackHedaya** [IBM-Swift/BlueSocket#23]
For some reason I am unable to 'import Socket.' I built and tested the BlueSocket-master. Am I missing something?

**Comment by billabt** [comment]
I need a bit more context. Can you give me a bit more context or an example?  Thanks.

**Comment by billabt** [comment]
Did you figure out your problem?  If not, feel free to re-open this issue.  Thanks.

**Comment by jackHedaya** [comment]
Apologies, I had a holiday and was unable to use a computer. This is what I did, please tell me where I went wrong:

1. Downloaded BlueSocket-master
2. Downloaded Package-Builder-fc7294807d24955ab720212b57472a49a630d348
3. Added Contents of Package-Builder-fc7294807d24955ab720212b57472a49a630d348 to BlueSocket-master/Package-Builder
4. Entered Terminal
5. Entered command: cd ~/Desktop/BlueSocket-master
6. Entered command: swift build
(Output: Compile Swift Module 'Socket' (3 sources))
7. Entered command: swift test
(Output: 

Compile Swift Module 'SocketTests' (1 sources)
Linking ./.build/debug/SocketPackageTests.xctest/Contents/MacOS/SocketPackageTests
Test Suite 'All tests' started at 2016-10-18 20:55:06.314
Test Suite 'SocketPackageTests.xctest' started at 2016-10-18 20:55:06.315
Test Suite 'SocketTests' started at 2016-10-18 20:55:06.315
Test Case '-[SocketTests.SocketTests testBlocking]' started.
Test Case '-[SocketTests.SocketTests testBlocking]' passed (0.004 seconds).
Test Case '-[SocketTests.SocketTests testConnect]' started.
Test Case '-[SocketTests.SocketTests testConnect]' passed (0.002 seconds).
Test Case '-[SocketTests.SocketTests testConnectPort0]' started.
Listener signature: Optional("Signature: family: inet, type: stream, protocol: tcp, address: Optional(Socket.Socket.Address.ipv4(__C.sockaddr_in(sin_len: 16, sin_family: 2, sin_port: 51164, sin_addr: __C.in_addr(s_addr: 0), sin_zero: (0, 0, 0, 0, 0, 0, 0, 0)))), hostname: Optional(\"0.0.0.0\"), port: 56519, secure: false")
Connect signature: Optional("Signature: family: inet, type: stream, protocol: tcp, address: Optional(Socket.Socket.Address.ipv4(__C.sockaddr_in(sin_len: 16, sin_family: 2, sin_port: 51164, sin_addr: __C.in_addr(s_addr: 0), sin_zero: (0, 0, 0, 0, 0, 0, 0, 0)))), hostname: Optional(\"0.0.0.0\"), port: 56519, secure: false")
Test Case '-[SocketTests.SocketTests testConnectPort0]' passed (0.003 seconds).
Test Case '-[SocketTests.SocketTests testConnectTo]' started.
Test Case '-[SocketTests.SocketTests testConnectTo]' passed (0.001 seconds).
Test Case '-[SocketTests.SocketTests testCreateIPV6]' started.
Test Case '-[SocketTests.SocketTests testCreateIPV6]' passed (0.000 seconds).
Test Case '-[SocketTests.SocketTests testDefaultCreate]' started.
Test Case '-[SocketTests.SocketTests testDefaultCreate]' passed (0.000 seconds).
Test Case '-[SocketTests.SocketTests testHostnameAndPort]' started.
Test Case '-[SocketTests.SocketTests testHostnameAndPort]' passed (0.001 seconds).
Test Case '-[SocketTests.SocketTests testIsReadableWritable]' started.
Error reported: Error code: -9996, Reason: Unavailable
Test Case '-[SocketTests.SocketTests testIsReadableWritable]' passed (0.000 seconds).
Test Case '-[SocketTests.SocketTests testListen]' started.
Test Case '-[SocketTests.SocketTests testListen]' passed (0.000 seconds).
Test Case '-[SocketTests.SocketTests testListenPort0]' started.
Listening port: 56523
Test Case '-[SocketTests.SocketTests testListenPort0]' passed (0.000 seconds).
Test Case '-[SocketTests.SocketTests testReadWrite]' started.
Listening on port: 1337

Connected to host: 127.0.0.1:1337
Accepted connection from: 127.0.0.1 on port 56524, Secure? false
	Socket signature: Signature: family: inet, type: stream, protocol: tcp, address: Optional(Socket.Socket.Address.ipv4(__C.sockaddr_in(sin_len: 16, sin_family: 2, sin_port: 14597, sin_addr: __C.in_addr(s_addr: 16777343), sin_zero: (0, 0, 0, 0, 0, 0, 0, 0)))), hostname: Optional("127.0.0.1"), port: 1337, secure: false

Read 34 from socket...
Response:
Hello, type 'QUIT' to end session

Wrote 'Hello from client...' to socket...
Server received from connection at 127.0.0.1:56524: Hello from client... 
Read 39 from socket...
Response:
Server response: 
Hello from client...

Sent quit to server...
Server received from connection at 127.0.0.1:56524: QUIT 
Test Case '-[SocketTests.SocketTests testReadWrite]' passed (0.001 seconds).
Test Suite 'SocketTests' passed at 2016-10-18 20:55:06.328.
	 Executed 11 tests, with 0 failures (0 unexpected) in 0.012 (0.013) seconds
Test Suite 'SocketPackageTests.xctest' passed at 2016-10-18 20:55:06.328.
	 Executed 11 tests, with 0 failures (0 unexpected) in 0.012 (0.013) seconds
Test Suite 'All tests' passed at 2016-10-18 20:55:06.328.
	 Executed 11 tests, with 0 failures (0 unexpected) in 0.012 (0.014) seconds

)

8. Entered Xcode
9. Created new project (macOS -> Game -> SpriteKit)
10. Cleared sample project
11. At the top of GameScene.swift, import Socket
12. **Error: No swift module 'Socket'**

Where did I go wrong?
