### ISSUE TITLE
No such module 'Socket'

### ISSUE THREAD

**Issue by jackHedaya** [IBM-Swift/BlueSocket#24]
I was unable to reopen the issue so I commented this on my old issue and created a new one.

Apologies, I had a holiday and was unable to use a computer. This is what I did, please tell me where I went wrong:

1. Downloaded BlueSocket-master
2. Downloaded Package-Builder-fc7294807d24955ab720212b57472a49a630d348
3. Added Contents of Package-Builder-fc7294807d24955ab720212b57472a49a630d348 to BlueSocket-master/Package-Builder
4. Entered Terminal
5. Entered command: cd ~/Desktop/BlueSocket-master
6. Entered command: swift build 

> (Output: Compile Swift Module 'Socket' (3 sources))

7. Entered command: swift test 

> (Output: Compile Swift Module 'SocketTests' (1 sources)
> Linking ./.build/debug/SocketPackageTests.xctest/Contents/MacOS/SocketPackageTests
> Test Suite 'All tests' started at 2016-10-18 20:55:06.314
> Test Suite 'SocketPackageTests.xctest' started at 2016-10-18 20:55:06.315
> Test Suite 'SocketTests' started at 2016-10-18 20:55:06.315
> Test Case '-[SocketTests.SocketTests testBlocking]' started.
> Test Case '-[SocketTests.SocketTests testBlocking]' passed (0.004 seconds).
> Test Case '-[SocketTests.SocketTests testConnect]' started.
> Test Case '-[SocketTests.SocketTests testConnect]' passed (0.002 seconds).
> Test Case '-[SocketTests.SocketTests testConnectPort0]' started.
> Listener signature: Optional("Signature: family: inet, type: stream, protocol: tcp, address: Optional(Socket.Socket.Address.ipv4(__C.sockaddr_in(sin_len: 16, sin_family: 2, sin_port: 51164, sin_addr: __C.in_addr(s_addr: 0), sin_zero: (0, 0, 0, 0, 0, 0, 0, 0)))), hostname: Optional(\"0.0.0.0\"), port: 56519, secure: false")
> Connect signature: Optional("Signature: family: inet, type: stream, protocol: tcp, address: Optional(Socket.Socket.Address.ipv4(__C.sockaddr_in(sin_len: 16, sin_family: 2, sin_port: 51164, sin_addr: __C.in_addr(s_addr: 0), sin_zero: (0, 0, 0, 0, 0, 0, 0, 0)))), hostname: Optional(\"0.0.0.0\"), port: 56519, secure: false")
> Test Case '-[SocketTests.SocketTests testConnectPort0]' passed (0.003 seconds).
> Test Case '-[SocketTests.SocketTests testConnectTo]' started.
> Test Case '-[SocketTests.SocketTests testConnectTo]' passed (0.001 seconds).
> Test Case '-[SocketTests.SocketTests testCreateIPV6]' started.
> Test Case '-[SocketTests.SocketTests testCreateIPV6]' passed (0.000 seconds).
> Test Case '-[SocketTests.SocketTests testDefaultCreate]' started.
> Test Case '-[SocketTests.SocketTests testDefaultCreate]' passed (0.000 seconds).
> Test Case '-[SocketTests.SocketTests testHostnameAndPort]' started.
> Test Case '-[SocketTests.SocketTests testHostnameAndPort]' passed (0.001 seconds).
> Test Case '-[SocketTests.SocketTests testIsReadableWritable]' started.
> Error reported: Error code: -9996, Reason: Unavailable
> Test Case '-[SocketTests.SocketTests testIsReadableWritable]' passed (0.000 seconds).
> Test Case '-[SocketTests.SocketTests testListen]' started.
> Test Case '-[SocketTests.SocketTests testListen]' passed (0.000 seconds).
> Test Case '-[SocketTests.SocketTests testListenPort0]' started.
> Listening port: 56523
> Test Case '-[SocketTests.SocketTests testListenPort0]' passed (0.000 seconds).
> Test Case '-[SocketTests.SocketTests testReadWrite]' started.
> Listening on port: 1337
> 
> Connected to host: 127.0.0.1:1337
> Accepted connection from: 127.0.0.1 on port 56524, Secure? false
> Socket signature: Signature: family: inet, type: stream, protocol: tcp, address: Optional(Socket.Socket.Address.ipv4(__C.sockaddr_in(sin_len: 16, sin_family: 2, sin_port: 14597, sin_addr: __C.in_addr(s_addr: 16777343), sin_zero: (0, 0, 0, 0, 0, 0, 0, 0)))), hostname: Optional("127.0.0.1"), port: 1337, secure: false
> 
> Read 34 from socket...
> Response:
> Hello, type 'QUIT' to end session
> 
> Wrote 'Hello from client...' to socket...
> Server received from connection at 127.0.0.1:56524: Hello from client... 
> Read 39 from socket...
> Response:
> Server response: 
> Hello from client...
> 
> Sent quit to server...
> Server received from connection at 127.0.0.1:56524: QUIT 
> Test Case '-[SocketTests.SocketTests testReadWrite]' passed (0.001 seconds).
> Test Suite 'SocketTests' passed at 2016-10-18 20:55:06.328.
> Executed 11 tests, with 0 failures (0 unexpected) in 0.012 (0.013) seconds
> Test Suite 'SocketPackageTests.xctest' passed at 2016-10-18 20:55:06.328.
> Executed 11 tests, with 0 failures (0 unexpected) in 0.012 (0.013) seconds
> Test Suite 'All tests' passed at 2016-10-18 20:55:06.328.
> Executed 11 tests, with 0 failures (0 unexpected) in 0.012 (0.014) seconds
> 
> )
> 

8. Entered Xcode
9. Created new project (macOS -> Game -> SpriteKit)
10. Cleared sample project
11. At the top of GameScene.swift, import Socket

**Error: No swift module 'Socket'**

I also noticed while trying to manually run BlueSocket-master/MakeFile I received the following output:

> (Computer):~ (user)$ /Users/(user)/Desktop/Socket\ Stuff/BlueSocket-master/Makefile ; exit;
> /Users/(user)/Desktop/Socket Stuff/BlueSocket-master/Makefile: line 18: -include: command not found
> /Users/(user)/Desktop/Socket Stuff/BlueSocket-master/Makefile: line 20: Package-Builder/build/Makefile:: No such file or directory
> /Users/(user)/Desktop/Socket Stuff/BlueSocket-master/Makefile: line 21: @echo: command not found
> fatal: Not a git repository (or any of the parent directories): .git
> logout
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.
> Deleting expired sessions...6 completed.
> 

And while running BlueSocket-master/Package-Builder/build/MakeFile:

> /Users/(user)/Desktop/Socket\ Stuff/BlueSocket-master/Package-Builder/build/Makefile ; exit;
> (Computer):~ (user)$ /Users/(user)/Desktop/Socket\ Stuff/BlueSocket-master/Package-Builder/build/Makefile ; exit;
> /Users/(user)/Desktop/Socket Stuff/BlueSocket-master/Package-Builder/build/Makefile: line 17: ifndef: command not found
> /Users/(user)/Desktop/Socket Stuff/BlueSocket-master/Package-Builder/build/Makefile: line 18: KITURA_CI_BUILD_SCRIPTS_DIR: command not found
> /Users/(user)/Desktop/Socket Stuff/BlueSocket-master/Package-Builder/build/Makefile: line 19: endif: command not found
> /Users/(user)/Desktop/Socket Stuff/BlueSocket-master/Package-Builder/build/Makefile: line 21: ${shell uname}: bad substitution
> /Users/(user)/Desktop/Socket Stuff/BlueSocket-master/Package-Builder/build/Makefile: line 24: syntax error near unexpected token "$(UNAME),'
> /Users/(user)/Desktop/Socket Stuff/BlueSocket-master/Package-Builder/build/Makefile: line 24: `ifeq ($(UNAME), Darwin)"
> logout
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.
> 

Where did I go wrong?

**Comment by billabt** [comment]
Clone the repository, then drag the `BlueSocket.xcodeproj` into your project.  That should make it available to your app.  The Package-Builder directory is used only for our Travis CI builds.  You shouldn't be using it.
