### ISSUE TITLE
Add documentation to BlueSocket

### ISSUE THREAD

**Issue by kweinmeister** [IBM-Swift/BlueSocket#3]
As a developer who is finding out about BlueSocket for the first time, I would like to see usage examples of the main features so that I can understand what BlueSocket can do and also to help me become productive quickly.

**Comment by billabt** [comment]
Makes perfect sense.  I've been considering adding one or two of the old test programs from ETSockets that would do exactly that.

**Comment by billabt** [comment]
Complete.
