### ISSUE TITLE
Plans for unix socket support?

### ISSUE THREAD

**Issue by PuerkitoBio** [IBM-Swift/BlueSocket#30]
Hello,

I see you already support TCP and UDP (IPv4 and IPv6), are there any plans to support UNIX sockets? It is presumably doable via the `create(fromNativeHandle:address:)` static method, but there's some amount of tricky work to do to get the fd. Would be awesome to have that library provide similar support as the `net` package in Go's stdlib, all under the same unified and simple API (which is great btw).

Thanks,
Martin

**Comment by billabt** [comment]
Thanks.  I'm working on adding that support.  Shouldn't be too difficult.  Assuming I don't get sidetracked by my other projects, I hope to have it in by the end of the week.

Also, fyi, the UDP support is currently incomplete.  Someone was going to be submit a PR to add it but I guess he's lost interest.  That'll be next on my **TODO** list.

**Comment by rfdickerson** [comment]
Do we have a use-case for the UDP socket yet? Maybe the Applications team could come up with something interesting like a multiplayer game server or video streaming.

**Comment by carlbrown** [comment]
I'd use UDP Sockets for the upcoming `memcache` client if they were available (assuming, of course, that I can get writing the `memcache` client moved to the top of my ToDo list).

**Comment by billabt** [comment]
I'm going to get the UNIX sockets working first.  Then I'll go after the UDP stuff.  I've already got the APIs for UDP in already but they don't do anything except throw a *NOT SUPPORTED* exception.

**Comment by carlbrown** [comment]
@billabt: No rush on my account.  Memcache can use either TCP or UDP (although I tend to prefer UDP on small clusters on switched networks), and most of the code I would be writing is the same in either case.

**Comment by billabt** [comment]
Support for UNIX sockets added as of version 0.12.3.  Closing issue.
