### ISSUE TITLE
Cocoapods specification

### ISSUE THREAD

**Issue by ileitch** [IBM-Swift/BlueSocket#47]
This isn't a PR because I refuse to fill out [this BS](https://github.com/IBM-Swift/CLA).

* Head on over to https://gist.github.com/ileitch/6c1560d77bc2171118c2cb310ebe8336 you'll find the spec
* Copy it into the root of this repo as `BlueSocket.podspec`
* If you haven't already, install Ruby
* Install cocoapods `gem install cocoapods`
* Run `pod trunk push BlueSocket.podspec`

Please read this [CocoaPods guide](https://guides.cocoapods.org/making/making-a-cocoapod.html) for more detail.

**Comment by billabt** [comment]
Supported as of version 0.12.35.
