### ISSUE TITLE
UNIX domain scoket file is removed on closing client socket.

### ISSUE THREAD

**Issue by mitsuse** [IBM-Swift/BlueSocket#49]
After accepting and closing a client socket, the request cannot reach the server anymore with a new client socket.

The socket file seems to be removed on closing not only server socket but client socket:
https://github.com/IBM-Swift/BlueSocket/blob/0.12.21/Sources/Socket.swift#L3230-L3236

Sources and commands to reproduce are as follow:

## Server（Swift 3.0.2,  BlueSocket 0.12.21)

```swift
import Foundation
import Socket

let socketPath: String = // same as $SOCKET_PATH

let serverSocket = try! Socket.create(family: .unix, type: .stream, proto: .unix)
try! serverSocket.listen(on: socketPath)

while true {
    let clientSocket = try! serverSocket.acceptClientConnection()
    defer { clientSocket.close() }
    var data = Data()
    try! clientSocket.read(into: &data)
    print(String(data: data, encoding: .utf8)!)
    try! clientSocket.write(from: "world!\n")
}
```

## Client（Bash)

```
$ echo 'Hello, ' | nc -U $SOCKET_PATH # OK.
$ echo 'Hello, ' | nc -U $SOCKET_PATH # Same as above but the server cannot accepts this (The request cannot reach the server).
```

Thanks.

**Comment by billabt** [comment]
Fixed in **BlueSocket 0.12.22**.  Thanks for reporting the problem.
