### ISSUE TITLE
TCP/IP buffer size

### ISSUE THREAD

**Issue by RenniePet** [IBM-Swift/BlueSocket#51]
This isn't an issue, it's just a request for advice. 

I see you've set the default buffer size to 4 KB. I once wrote some TCP/IP I/O for C#, and I automatically assumed a buffer size of 64 KB would be best. But I don't really know. Do you know of any reasons why 4 KB or 64 KB is best or inadvisable? Thanks.

**Comment by billabt** [comment]
Early on in development, we ran some tests and determined that the *4 KB* default buffer was the best size for *general* overall performance.  But there's no reason why you couldn't adjust that buffer size by setting the `<-socket instance->.readBufferSize` to some other value and see what kind of performance results you get.  For example, it would probably a good idea to increase the size of the read buffer if you were writing file or media server using *Socket*.  Hope this helps.

I'm gonna close this issue for now but feel free to comment further or re-open it if you have anymore questions.
