### ISSUE TITLE
Bad access error in Socket.listen (path) -> Signature -> line 552 

### ISSUE THREAD

**Issue by radetsky** [IBM-Swift/BlueSocket#59]
Hi guys, 

I got a strange error. Steps to reproduce is simple. 
1. Make a new project - command line tool for macOS in Xcode 8. 
2. Copy Socket files as sources to new project. CocoaPods does not link framework to command line tool. 
3. Make simple UNIX (!) Socket server 
4. Run it - must be ok. 
5. Change scheme to build release  
6. Released command line tool will break in Socket.swift: 552-562 lines with remoteAddr operations.  

I commented these lines and do not use self.address and it works fine. 
PS. I know this is a dirty hack to create command line tool. I know how swift package manager works, but I got big project in Xcode and integrate your framework with it is very hard to support later (build scripts, et cetera )

**Comment by billabt** [comment]
This should be fixed in the latest build (0.12.54).

**Comment by radetsky** [comment]
Thank you very much. :)
