### ISSUE TITLE
EXC_BAD_ACCESS connecting to a unix socket on MacOS

### ISSUE THREAD

**Issue by davidgyoung** [IBM-Swift/BlueSocket#68]
I am getting  EXC_BAD_ACCESS trying to connect to a unix socket on MacOS 10.12.4 and IBM-Swift/BlueSocket 0.12.46.

 If I change this to be a TCP socket it works just fine.

    self.clientSocket = try Socket.create(family: Socket.ProtocolFamily.unix, type: Socket.SocketType.stream, proto: Socket.SocketProtocol.unix)
    print("Connecting to server")
    try self.clientSocket?.connect(to: "/tmp/observer_collector") // crashes with EXC_BAD_ACCESS

When this happens, I see nothing on the file system at the /tmp/observer_collector, despite executing code that should create the socket with the following code (which does not crash and does not raise any exceptions):

    self.serverSocket = try Socket.create(family: Socket.ProtocolFamily.unix, type: Socket.SocketType.stream, proto: Socket.SocketProtocol.unix)
    try self.serverSocket.listen(on: "/tmp/observer_collector")

I'm not sure if the socket got created successfully or not, since I cannot see it on the file system.  Regardless, I don't think the client connection code should crash.

Here's the stack trace:

```
Thread 3Queue : com.apple.root.background-qos (concurrent)
#0	0x000000010012470a in Socket.Signature.init(socketType : Socket.SocketType, proto : Socket.SocketProtocol, path : String?) throws -> Socket.Signature? [inlined] ()
#1	0x00000001001246f7 in specialized Socket.connect(to : String) throws -> () at /Users/dyoung/workspace/wireless-registry/macos-observer/Observer/Carthage/Checkouts/BlueSocket/Sources/Socket.swift:1866
#2	0x00000001000134e7 in SocketClient.(start() -> Bool).(closure #1) at /Users/dyoung/workspace/wireless-registry/macos-observer/Observer/Observer/SocketClient.swift:27
#3	0x0000000100002247 in thunk ()
#4	0x0000000100c47cfe in _dispatch_call_block_and_release ()
#5	0x0000000100c3e78c in _dispatch_client_callout ()
#6	0x0000000100c40cc1 in _dispatch_root_queue_drain ()
#7	0x0000000100c4071d in _dispatch_worker_thread3 ()
#8	0x0000000100cb5812 in _pthread_wqthread ()
#9	0x0000000100cb52ed in start_wqthread ()
Enqueued from com.apple.main-thread (Thread 1)Queue : com.apple.main-thread (serial)
#0	0x0000000100c544ca in _dispatch_queue_push ()
#1	0x00000001008e474b in DispatchQueue.async(group : DispatchGroup?, qos : DispatchQoS, flags : DispatchWorkItemFlags, execute : @convention(block) () -> ()) -> () ()
#2	0x00000001000130aa in SocketClient.start() -> Bool at /Users/dyoung/workspace/wireless-registry/macos-observer/Observer/Observer/SocketClient.swift:60
#3	0x000000010000b4d7 in ViewController.viewDidAppear() -> () at /Users/dyoung/workspace/wireless-registry/macos-observer/Observer/Observer/ViewController.swift:51
#4	0x000000010000b5e2 in @objc ViewController.viewDidAppear() -> () ()
#5	0x00007fffcbe19634 in -[NSViewController _sendViewDidAppear] ()
#6	0x00007fffcbe1932b in -[NSView(NSInternal) _windowDidOrderOnScreen] ()
#7	0x00007fffcbe193de in -[NSView(NSInternal) _windowDidOrderOnScreen] ()
#8	0x00007fffcc57daa8 in -[NSWindow _reallyDoOrderWindowAboveOrBelow:relativeTo:findKey:forCounter:force:isModal:] ()
#9	0x00007fffcbe15a9e in -[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:] ()
#10	0x00007fffcbe15633 in -[NSWindow orderWindow:relativeTo:] ()
#11	0x00007fffcbec7f7b in -[NSWindow makeKeyAndOrderFront:] ()
#12	0x00007fffd3c94519 in -[QLSeamlessDocumentOpener showWindow:contentFrame:withBlock:] ()
#13	0x00007fffcbec7107 in -[NSWindowController showWindow:] ()
#14	0x00007fffcbc9a0fe in NSApplicationMain ()
#15	0x00000001000093dc in main at /Users/dyoung/workspace/wireless-registry/macos-observer/Observer/Observer/main.swift:24
#16	0x00007fffe3941235 in start ()
```

And here is a screenshot of XCode:

<img width="1462" alt="screen shot 2017-05-25 at 12 28 53 pm" src="https://cloud.githubusercontent.com/assets/1044849/26460151/caaf1604-4146-11e7-9909-8a1a0fa42e9e.png">

**Comment by billabt** [comment]
You're right, it shouldn't crash.  I'll try to take a look at it...  Will advise.

**Comment by mna** [comment]
I can confirm the same issue on macOS 10.12.5 and BlueSocket 0.12.53. I used `redis-server --unixsocket <somepath> --unixsocketperm 700` as server and tested that it connected correctly with `redis-cli -s <somepath>`. This code fails with the bad access error in the call to connect:

```
    socket = try Socket.create(family: .unix, proto: .unix)
    try socket.connect(to: path)
```

Thanks,
Martin

**Comment by mna** [comment]
I investigated a bit more, I think I have a fix, I'll send a PR soon.

**Comment by billabt** [comment]
Sounds good. I look forward to it. Thanks.

**Comment by davidgyoung** [comment]
I am also happy to test when a PR is ready

**Comment by mna** [comment]
Cool thanks. Here's a minimal Xcode project to reproduce the issue (it's a plain Cocoa project with BlueSocket as Embedded Binary, installed via Carthage. UI is just a window with textbox to enter a path and a button to try to connect using the two lines I pasted earlier): https://github.com/mna/BlueSocketUnixSocketTest.

My first attempt was to write a failing test in BlueSocket, but there are already UNIX socket tests, and they pass fine on my macbook both via `swift test` and Xcode, so I was a bit puzzled (still am, though the minimal project proves the issue in that specific context).

Fix coming up, we can discuss details on the PR.
