### ISSUE TITLE
Add podspec to cocoapods?

### ISSUE THREAD

**Issue by niklassaers** [IBM-Swift/BlueSocket#69]
First of all, thanks for a great project.

You are maintaining BlueSocket.podspec, but I cannot see it listed on Cocoapods.org when I search for it. Would you mind submitting it there? Otherwise I'll gladly submit it for you.

Background: I'm in a team maintaining Theo, a Swift driver for the neo4j database. We've just added Bolt support (a transfer protocol) and it uses BlueSocket and BlueSSLService for its networking. It's all set up and ready for release through the Swift Package Manager, but I'd like to maintain support through CocoaPods and Carthage as well

**Comment by billabt** [comment]
@niklassaers:  Feel free to add both _BlueSocket_ and _BlueSSLService_ to the Cocoapods repo.  Thanks for the contribution and the help.

**Comment by niklassaers** [comment]
Hi, I went to publish but got I was told only Matthaus Woolard or tfranklin had permission to do this. If any of them could type "pod trunk push" while in the BlueSocket directory that'd be great  (ping @tfrank64) (alternatively give me permission to publish, but I'm not quite sure what's needed for that)

**Comment by billabt** [comment]
I'll check it out.

**Comment by tfrank64** [comment]
@niklassaers @billabt I've published both repos to cocoapods.

**Comment by niklassaers** [comment]
Thank you :-)
