### ISSUE TITLE
How to set timeout for connect?

### ISSUE THREAD

**Issue by SelvaBalasubramanian** [IBM-Swift/BlueSocket#76]
I need to set timeout for socket.connect(ip ,port) how can I do it?

**Comment by billabt** [comment]
The easiest way is to use the _isReadableOrWritable_ function.  The basic steps are as follows:
1. Create the socket.
2. Set the socket to non-blocking mode using _setBlocking(mode: false)_.
3. Issue the connect.
4. Call _isReadableOrWritable(waitForever: false, timeout: yourTimeout)_ function on the socket using your desired timeout.
5. If the returned tuple indicates that it's _writable_, you're connected, if not, the timeout has occurred.
6. Reset the blocking mode back to blocking if desired...

**Comment by SelvaBalasubramanian** [comment]
I tried but the same problem occurs.The problem what I am facing is when the socket.connect(ip, port) starts executing it waits for some time to connect.

**Comment by SelvaBalasubramanian** [comment]
here is the code!! 
I need to implement a network scan...for availability of a particular ip and port...
`    
    func searchController(){
        
        let ipString = "192.168.1."
        let port = 8286
        var k = 1
        
        let socket = try? Socket.create()
        while(k <= 255){

            let ip = ipString + "\(k)"
            try? socket?.setBlocking(mode: false)
            print("function entered")
                try?  socket?.connect(to: ip , port: Int32(port))
               print(k)
            let result = try? socket?.isReadableOrWritable(waitForever: false, timeout: UInt(0
            ))
            
            if result??.writable != nil {
                if result.unsafelyUnwrapped?.writable == true{
                    print(ip  + " " + "\(port)" )
                }
                }else{
                    socket?.close()
                }
         k +=  1
  
    }
        
    }`

**Comment by SelvaBalasubramanian** [comment]
i tried but it still waits in  socket?.connect(to: ip , port: Int32(port))

**Comment by mna** [comment]
I can confirm the same behaviour for me on Darwin, see https://github.com/mna/testconnecttimeout to reproduce. Blocks on the call to `socket.connect` even though the socket is in non-blocking mode.

**Comment by billabt** [comment]
Fixed in 0.12.60.
