### ISSUE TITLE
Bind UDP sockets to source port/address

### ISSUE THREAD

**Issue by jpap** [IBM-Swift/BlueSocket#78]
I'd like to control the source port (and optionally, interface/IP address) of outbound UDP packets.

This can be achieved by using bind (2).  It would be nice to have this as an additional API on the Socket class.

**Comment by billabt** [comment]
What would you like the API to look like?  It'll be easier to determine how best to implement it if I had a bit more of an idea of what you want.  Thanks.

**Comment by Joebayld** [comment]
Agreed. 

This is likely what he is referencing: 

http://cocoadocs.org/docsets/CocoaAsyncSocket/7.3.1/Classes/GCDAsyncUdpSocket.html#//api/name/bindToPort:interface:error:

**Comment by billabt** [comment]
I believe this requirement is satisfied with the changes included in version _1.0.38_.  Please re-open if you think otherwise. 😉

**Comment by Joebayld** [comment]
Circling back on this. I'm not sure it has been resolved. How would one bind an outbound socket to an interface?
