### ISSUE TITLE
UDP broadcast example

### ISSUE THREAD

**Issue by SolomonViveros** [IBM-Swift/BlueSocket#80]
Is there any example usage available to demonstrate setting the socket options[if necessary] to allow for a UDP broadcast using the  .write(from:,to:) command? 

When I write to "192.168.1.255" I get a Udp write Error on a test network that allows broadcasts.

**Comment by billabt** [comment]
What error are you getting?  Can you show me some code?  Thanks.

**Comment by SolomonViveros** [comment]
It shows an SOCKET_ERR_WRITE_FAILED - Permission Denied

```
UdpAsciiBuffer[0] = 48
UdpAsciiBuffer[1] = 49
UdpAsciiBuffer[2] = 50
UdpAsciiBuffer[3] = 51
        
let addr = Socket.createAddress(for: "192.168.1.255", on: UdpPort)
           
do
     {
     try TestUdpSocket?.write(from: UdpAsciiBuffer, to: addr!)
      }
catch let error
    {
    print("Udp write Error")
    }
```
UdpPort = 1234
If the address is specified to a unique IP, data is sent, but when the IP is set to 255 an error is returned.

**Comment by billabt** [comment]
This is fixed in the latest release, _0.12.58_.  I added a new API, _udpBroadcast(enable: Bool)_, that you should call after creating the socket and before attempting to write to it.  See the documentation in the _README.md_ for more info.

**Comment by SolomonViveros** [comment]
After updating and setting UdpBroadcast to true, a Permission denied error is returned when using the testReadWriteUDP() example function where hostname = "192.168.1.255" and port set to 1234.

Are you able to confirm a "Hello from UDP" udp broadcast across the network using the testReadWriteUDP example function?

**Comment by SolomonViveros** [comment]
Awesome! Works now. Thanks!
