### ISSUE TITLE
Do not use SO_REUSEPORT on WSL

### ISSUE THREAD

**Issue by pixelspark** [IBM-Swift/BlueSocket#81]
In PR https://github.com/IBM-Swift/BlueSocket/pull/61 (https://github.com/IBM-Swift/BlueSocket/pull/61/commits/e639a3fd5e15445f32319f26936f0daf5fea0ca3), use of the SO_REUSEPORT socket option was added. This however causes issues on Windows Subsystem for Linux (WSL), which does not (and will likely never) support SO_REUSEPORT. 

Strace shows the following:

````
setsockopt(15, SOL_SOCKET, SO_REUSEPORT, [1], 4) = -1 ENOPROTOOPT (Protocol not available)
````

By the way, SO_REUSEADDR works without issue on WSL:

````
setsockopt(15, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
````

Please consider adding a way to disable the use of SO_REUSEPORT, or do not fail with an exception (but rather silently) when the call to setsockopt fails with ENOPROTOOPT (at least on Linux). Unfortunately it is not possible to detect WSL at compile-time, as the userland is actually Ubuntu (or other Linux). A third option would be to perform detection at runtime (or perform some other check to see whether SO_REUSEPORT is available) but then again, that is probably more complicated than simply ignoring an ENOPROTOOPT error.

**Comment by billabt** [comment]
Fixed in the latest release, _0.12.57_.  It now will fail silently should the _errno_ be set to *ENOPROTOOPT*.  Thanks.
