### ISSUE TITLE
Package Manager Documentation missing ".git"

### ISSUE THREAD

**Issue by vjbose** [IBM-Swift/BlueSocket#82]
dependencies: [
		.Package(url: "https://github.com/IBM-Swift/BlueSocket", majorVersion: <majorVersion>, minor: <minor>)
	]
Should be 	dependencies: [
		.Package(url: "https://github.com/IBM-Swift/BlueSocket.git", majorVersion: <majorVersion>, minor: <minor>)
	]

**Comment by billabt** [comment]
Fixed.  Thanks.
