### ISSUE TITLE
Disable watchOS in the Podspec

### ISSUE THREAD

**Issue by JacopoMangiavacchi** [IBM-Swift/BlueSocket#87]
I saw watchOS is a supported platform on the pod and I tried to use it on a watchOS project but unfortunately I discovered Posix/BSD/Darwin sockets are not supported on real Apple Watch devices.  

Sockets only works on simulator.

Basically when the BlueSocket initializer [Socket.swift init()] try to create a Darwin.socket handle on a real device it get a SOCKET_INVALID_DESCRIPTOR and then throw an exception.

Indeed all Foundation/iOS APIs based on Posix/BSD/Darwin sockets (i.e. NSURLSessionStreamTask, NSStream and CFSocketStream) are flagged as __WATCHOS_PROHIBITED on watchOS.

NSURLSession (for HTTP) is the only network API available on watchOS

The simulator works because it doesn’t apply sandbox restrictions.

Jacopo Mangiavacchi

**Comment by JacopoMangiavacchi** [comment]
If you need more context info I was trying to create an .ipv4 socket on datagram/udp on watchOS 4.0

try Socket.create(family: .inet, type: .datagram, proto: .udp)

**Comment by billabt** [comment]
Fixed in the latest release.  Thanks for the report.
