### ISSUE TITLE
if socketfd not available will get signal SIGPIPE and fail.

### ISSUE THREAD

**Issue by vicalloy** [IBM-Swift/BlueSocket#88]
In function `private init(family: ProtocolFamily, type: SocketType, proto: SocketProtocol) throws ` will set SO_NOSIGPIPE to socketfd.
But in function `public func connect(to host: String, port: Int32, timeout: UInt = 0)` will reset socketfd, new socketfd don't set SO_NOSIGPIPE. if socketfd is not available will get signal SIGPIPE.

**Comment by billabt** [comment]
Fixed in _version 0.12.69_.  Thanks.
