### ISSUE TITLE
how to use in objective-c?

### ISSUE THREAD

**Issue by italoBianchini** [IBM-Swift/BlueSocket#91]
how to use in objective-c? There is nothing like it on the market!

**Comment by billabt** [comment]
Unfortunately, _BlueSocket_ can _only be called_ from a _Swift_ module.  It can be used in a _hybrid app_ but can only be called from Swift.  You could write a small Swift module that exposes itself to Objective-C using the _@objc_ keyword and then write _small shim functions_ that call into _BlueSocket_.  At this time, that's the only way to use it from Objective-C.  _BlueSocket_ is using many of the _advanced features_ of the Swift language that are not _fully_ compatible with Objective-C.

**Comment by italoBianchini** [comment]
thank you very much
