### ISSUE TITLE
App extension api only

### ISSUE THREAD

**Issue by mcfedr** [IBM-Swift/BlueSocket#92]
Would be great if you ticked the box 'App extension api only' in the xcode project.

**Comment by billabt** [comment]
Can you give me an idea what you’re planning on using it for?  Right now due to bug in Xcode, ticking this box results in exposing internal and private APIs something I’d like to avoid. Thanks.

**Comment by mcfedr** [comment]
Hah, thats interesting, I am using it with a NetworkExtension PacketTunnelProvider

**Comment by purkylin** [comment]
Whether can use it in NetworkExtension?

**Comment by billabt** [comment]
If needed, just flip the switch for your local project.  That bug is still present...
