### ISSUE TITLE
SO_REUSEPORT could lead to accidental port sharing

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/BlueSocket#94]
I just discovered that I am allowed to start multiple instances of Kitura on the same port, without error (and in fact, on Linux, requests get distributed across them).  This is due to `SO_REUSEPORT` which is set on by default since PR #61 .

The PR implies it was targeting sharing only for _UDP_ ports, but this affects all listeners.  I wonder if this was intentional?

Prior to this change Kitura would have failed to start with a message like:
```
[2017-10-11T15:32:38.010Z] [ERROR] [Kitura.swift:91 start()] Error listening on port 8080: Error code: -9992(0x-2708), Address already in use. Use server.failed(callback:) to handle
```
...however now that `SO_REUSEPORT` is set, this will no longer happen.

This led to me accidentally running two unrelated Kitura processes on the same port and getting some very confusing behaviour.  I can appreciate the usefulness of this option, but I'd think it would be safer as an opt-in - perhaps an optional flag to `listen()` - rather than a default, since it's rather easy to accidentally leave an old instance of a server running otherwise.

**Comment by billabt** [comment]
I can look into making it _optional_ but with current behavior as the default.  Would that work?

**Comment by djones6** [comment]
Thanks - I think that would work.

**Comment by billabt** [comment]
Added the new parameter to _listen_ API.  See the README.md or code for more info.  Effective in version _0.12.74_.
