### ISSUE TITLE
Question: Is there any issues using this library with iOS 

### ISSUE THREAD

**Issue by k1x0r** [IBM-Swift/BlueSocket#95]
Hello, 

I use this library in my iOS project in which it communicates to server via custom protocol. And it's important to me to have the same code on linux side.

However I found recommendation from Apple:

"In iOS, POSIX networking is discouraged because it does not activate the cellular radio or on-demand VPN. Thus, as a general rule, you should separate the networking code from any common data processing functionality and rewrite the networking code using higher-level APIs."

And topics on StackOverflow:

https://stackoverflow.com/questions/25045829/how-can-i-activate-the-cellular-radio-in-ios-since-bsd-sockets-doesnt-activate

Could you clarify please is there any issues using the library with iOS. And do you have any information  about what changed since iOS 10 that allows to use this library in iOS (e.g. activating cellular radio/vpn on demand)

Thanks!

**Comment by billabt** [comment]
In my testing, there should be no issues using this library on iOS.  With that said, the answer to the topic you referenced on StackOverflow is correct.  Using _BlueSocket_ to open a **TCP** connection _will activate_ the radio and/or on-demand VPN.  However, if you want to use **UDP**, you'll have to _first_ open a **TCP** socket and either _listen_ or _connect_ (note: doesn't have to go anywhere) with it to trigger the activation.  Once activated, your **UDP** connections should work properly.  Let me know if you have any issues with this or simply re-open the issue.  Thanks.

**Comment by billabt** [comment]
To keep your code cross platform, you could do something like the following (if using **UDP**):
```
--- Beginning of function that does something with UDP...
#if os(iOS)
    /// Activate the radio...
    let activateSocket = Socket.create()
    try activateSocket.listen(on: <Some valid port>)
    activateSocket.close()
#endif
--- Continue doing something with UDP...
```
