### ISSUE TITLE
README outdated

### ISSUE THREAD

**Issue by xbainbain** [IBM-Swift/BlueSocket#96]
In **Complete Example**, this line
```Swift
try self.listenSocket = Socket.create(family: .inet6)
```
create a an IPV6 socket.So try `telnet 127.0.0.1 1337` would not success. It would show:
```
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```
So change it to `.inet` or use `telnet ::1 1337` instead will be fine.

And it seems that swift 4 doesn't support the use of`.Package(url: String, majorVersion: Int, minor: Int),` it will cause a compile error. It would be nicer if that be indicated in README.md

**Comment by billabt** [comment]
They'll be a new release coming out in a few days.  I'll address these concerns and close the issue at that time.  Thanks for the input.

**Comment by xbainbain** [comment]
Haha, okay. Looking forward to the new release. 😀

**Comment by billabt** [comment]
Fixed in version _0.12.75_.
