### ISSUE TITLE
How to implement read how many bytes to data

### ISSUE THREAD

**Issue by ffchung** [IBM-Swift/BlueSocket#97]
How to implement read how many bytes to data? Thanks

socket.read(into: &readData, len:Int)

**Comment by billabt** [comment]
There's a function that does already.  Here's the excerpt from the doc:
```
- read(into buffer: UnsafeMutablePointer<CChar>, bufSize: Int, truncate: Bool = false)`
```
- This function allows you to read data into a buffer of a specified size by providing an *unsafe* pointer to that buffer and an integer the denotes the size of that buffer.  This API (in addition to other types of exceptions) will throw a `Socket.SOCKET_ERR_RECV_BUFFER_TOO_SMALL` if the buffer provided is too small, unless `truncate = true` in which case the socket will act as if only `bufSize` bytes were read (unretrieved bytes will be returned in the next call). If `truncate = false`, you will need to call again with proper buffer size (see `Error.bufferSizeNeeded`in *Socket.swift* for more information).

It'd be rather trivial to write an _extension_ to **BlueSocket** to allow you to use this API to do that read and then return either a _Data_ or _NSData_.

Re-open this issue if you have any questions.  Thanks.

**Comment by eugenijusr** [comment]
I had the same problem and this is what worked for me:

```swift
extension Socket {
    func read(into data: inout Data, size: Int) throws -> Int {
        let pointer = UnsafeMutablePointer<Int8>.allocate(capacity: size)
        defer {
            pointer.deallocate(capacity: size)
        }
        
        let bytesRead = try self.read(into: pointer, bufSize: size, truncate: true)
        data.append(UnsafeBufferPointer(start: pointer, count: bytesRead))

        return bytesRead
    }
}
```

And then given you have the exepected `responseLength`.

```swift
var responseData = Data()
var bytesRead = 0

while bytesRead < responseLength {
    let newBytesRead = try self.socket.read(into: &responseData, size: responseLength - bytesRead)
    if newBytesRead == 0 {
        throw Error("Read failed")
    }
    
    bytesRead += newBytesRead
}
```
