### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by robreuss** [IBM-Swift/BlueSocket#98]
I get a "connection refused" message when attempting to connect in almost all contexts.

When I run the GitHub sample or my own code, I'm only able to make a TCP connection when running both the client and server on the same machine.  For example, if I compile the sample as a macOS app, I can connect from telnet on that machine (using `telnet localhost 1337` - `telnet 127.0.0.1 1337` does not work).  However, if I try to connect to that service from a different machine over the local network (e.g. `telnet 192.168.86.115`) I get a "connection refused" message.  

I have also tried making the same type of machine-to-machine connect using a virtual machine with networking configured for host-only, so connectivity does not go through my router, and I get the same result.  

I have tried making these connections between different devices (iOS, macOS) to ensure that no single device could be the point of failure, and get consistent results.

I have written custom code for both TCP client and server and get the same "Connection refused" message.

If I were not operating on a local network, this would seem to obviously be an issue with a firewall/port forwarding, but all connection attempts have been local.  Waving a dead chicken at it, I swapped the router and got the same results.

I apologize if I'm missing something obvious, but BlueSocket (probably my improper use of it) seems to be the one unknown aspect.  However, I'm using the sample, so I'm baffled as to how I could be uniquely having this problem.

**Comment by billabt** [comment]
There was an error in the doc.  The problem is that the example code is using _IPV6_ and the _telnet command specified by the doc only works for IPV4_.  Try running the same code and connecting via the following command:
```
telnet ::1 1337
```
If that doesn't work, go ahead and re-open this issue but I'm pretty sure this is going to solve your problem.

**Comment by robreuss** [comment]
Fixed.  Thank you sir!

**Comment by billabt** [comment]
No problem. My fault for faulty doc. Thanks.
