### ISSUE TITLE
Can't Include BlueSocket As Linked Framework

### ISSUE THREAD

**Issue by b69ca** [IBM-Swift/BlueSocket#99]
Hello,

Is is possible you can help be resolve this issue? I have tried searching the web and tried extensively to apply to suggestions provided to no avail. For reference I am using Xcode 9.

- I cloned the latest tag for the BlueSocket repository.
- I created a new project (Swift Command Line Project) and then added the Xcode Project file for BlueSocket
- I added the Framework (socket.framework) into Linked Frameworks and Libraries.
- I added "import Socket" into my main.swift file.

Now my project builds fine and even runs, however when it runs I see the following error:

```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/jonw/Library/Developer/Xcode/DerivedData/BlueSay-abzdpmcqyyyltzdeccssbhoupawb/Build/Products/Debug/Socket.framework/Versions/A/Socket
  Reason: image not found

```
I have tried to set the swift version to 4 on the framework to match the version of my project however this doesn't seem to address the issue either.

Am I missing something? Any help would be appreciated.

Cheers,
Jon

**Comment by billabt** [comment]
- In your project, go to the **Build Settings_**.
- Set the **Runpath Search Paths** to "$(TOOLCHAIN_DIR)/usr/lib/swift/macosx @executable_path"
- Set the **Framework Search Paths** to "$(inherited) $(PLATFORM_DIR)/Developer/Library/Frameworks"
- Add _SWIFT_FORCE_DYNAMIC_LINK_STDLIB=1_ and _SWIFT_FORCE_STATIC_LINK_STDLIB=0_ as **User Defined** fields (if not already present).

That should fix it.  This only appears necessary when creating _command line apps_ on **macOS**.

Re-open if you have any problems.

**Comment by robreuss** [comment]
My issue is essentially the same so I thought it made sense to describe it here.  In my case, I'm attempting to build a framework containing BlueSocket as a dependency.  I'm able to build that framework without errors, but will I try to utilize it in an iOS view project, it builds but does not run on the device or simulator.  It gives me this error message:  

`dyld: Library not loaded: @rpath/Socket.framework/Socket
  Referenced from: /Users/robreuss/Library/Developer/CoreSimulator/Devices/1CCF9684-F8B6-457B-B276-44D5B8B13CAD/data/Containers/Bundle/Application/96AB7C0B-4F9D-4B5B-8533-748EFEB18D50/TestIOSPeripheral.app/Frameworks/TestIOSFramework.framework/TestIOSFramework
  Reason: image not found`

It seems like BlueSocket is not being contained in my framework (it's parent framework): TestIOSFramework.

I've tried your instructions above as appropriate to the iOS view app but get that error.  Any thoughts would be most appreciated.
